[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-fund --no-audit"

# Ensure proper caching of immutable assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers (basic hardening)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Redirects for SPA fallback (also add _redirects for clarity)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
